# Generated by Django 5.2 on 2025-05-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_driver', models.CharField(max_length=50, verbose_name='ФИО водителя')),
                ('waiting_date', models.DateField(verbose_name='Дата ожидания')),
                ('departure_date', models.DateField(verbose_name='Дата отъезда')),
                ('date', models.DateTimeField(verbose_name='Время')),
                ('count', models.IntegerField(verbose_name='Количество мест')),
                ('in_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incity', to='main.city', verbose_name='От куда')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tocity', to='main.city', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver', verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
    ]
