# Generated by Django 5.2 on 2025-05-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_driver_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default=1, max_length=50, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
