# Generated by Django 5.2 on 2025-05-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_driver_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
