# Generated by Django 5.2 on 2025-05-06 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_driver_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='in_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incity', to='main.city', verbose_name='От куда'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='to_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tocity', to='main.city', verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='people',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.driver', verbose_name='Пассажир'),
        ),
    ]
